/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package produto.view;

import produto.utils.ManipularImagem;
import produto.controller.ProdutoController;
import java.awt.image.BufferedImage;
import java.io.File;
import java.math.BigDecimal;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Thiago
 */
public class NovoProduto extends javax.swing.JDialog {
    private static NovoProduto INSTANCE = null;
    BufferedImage imagemBuffer = null;
  
    //Construtor privado para Padrão Singleton
    private NovoProduto (java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /*
    ** Verifica se há uma instancia da Jdialog,
    ** caso não haja ele cria e retorna a instância da mesma
    */
    public static NovoProduto getInstance() {
        if(INSTANCE == null){
            INSTANCE = new NovoProduto(new javax.swing.JFrame(), true);
        } 
            return INSTANCE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lbl_nome_produto = new javax.swing.JLabel();
        txt_nome_produto = new javax.swing.JTextField();
        lbl_preco = new javax.swing.JLabel();
        txt_preco = new javax.swing.JTextField();
        lbl_imagem = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();
        btn_confirmar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        main_panel.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 430, 10));
        main_panel.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, 310));

        lbl_nome_produto.setText("Nome Produto:");
        main_panel.add(lbl_nome_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        main_panel.add(txt_nome_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 190, -1));

        lbl_preco.setText("Preço:");
        main_panel.add(lbl_preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        main_panel.add(txt_preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 190, -1));

        lbl_imagem.setText("Imagem:");
        main_panel.add(lbl_imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        ImageIcon placeholder;
        placeholder = new ImageIcon(NovoProduto.class.getResource("/resources/placeholder.jpg"));

        imagem.setIcon(placeholder);
        imagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagemMouseClicked(evt);
            }
        });
        main_panel.add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 190, 140));

        btn_confirmar.setText("Confirmar");
        btn_confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_confirmarMouseClicked(evt);
            }
        });
        main_panel.add(btn_confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        btn_cancelar.setText("Cancelar");
        main_panel.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_confirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmarMouseClicked
        ProdutoController produtoCtrl = null;
        JDialog dialog;
        BigDecimal preco;
        
        /*
        ** Valida os dados usando a controller dos produtos passando os parâmetros da view
        ** Faz a conversão do preco informado para Double
        ** 
        */
        try {
             preco = new BigDecimal(txt_preco.getText());              
             produtoCtrl = new ProdutoController(txt_nome_produto.getText(), preco, ManipularImagem.getImgBytes(imagemBuffer));
             
             if(produtoCtrl.validarDados()) {
                 produtoCtrl.cadastrarProduto();
                 dispose();
             }
        } catch(NumberFormatException e) {
            dialog = new JOptionPane("Erro ao coverter preco! Por favor valide o valor informado.", JOptionPane.ERROR_MESSAGE,JOptionPane.DEFAULT_OPTION).createDialog(" Erro no valor informado"); 
            dialogOptions(dialog);
        } catch(Exception e) {
            dialog = new JOptionPane(e.getMessage(), JOptionPane.ERROR_MESSAGE,JOptionPane.DEFAULT_OPTION).createDialog(" Falha"); 
            dialogOptions(dialog);
        }
        
        
    }//GEN-LAST:event_btn_confirmarMouseClicked
    /* 
    * Quando clicar no placeholder da image aparece opção para selectionar imagem
    */
    private void imagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagemMouseClicked
        JFileChooser fileChooser = new JFileChooser();
       
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File arquivo = fileChooser.getSelectedFile();

            try {
                imagemBuffer = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 160, 160);
                imagem.setIcon(new ImageIcon(imagemBuffer));
            } catch (Exception ex) {
               System.out.println(ex.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um arquivo!!!");
        }
    }//GEN-LAST:event_imagemMouseClicked
    /*
    * Opções usadas para mostrar mensagens de erro na tela durante a validação
    */
    public void dialogOptions(JDialog dialog) throws SecurityException {
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
        dialog.dispose();
    }


  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_confirmar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel lbl_imagem;
    private javax.swing.JLabel lbl_nome_produto;
    private javax.swing.JLabel lbl_preco;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField txt_nome_produto;
    private javax.swing.JTextField txt_preco;
    // End of variables declaration//GEN-END:variables
}
